name: ROOT Geant4 Dockerimage build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Docker/HEP/ROOT-Geant4-Garfieldpp/Dockerfile --tag lobis/root-geant4-garfieldpp:latest
